name: PDF build
on:
  push:
    branches: [ "main" ]

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: ""

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""

      - name: Build PDF
        run: "nix build --no-link --print-out-paths --print-build-logs | xargs -I{} cp {} Thesis.pdf"

      - name: Store PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Thesis.pdf

  verify:
    needs: build
    runs-on: "ubuntu-24.04"
    container: "ghcr.io/mff-cuni-cz/cuni-thesis-validator:latest"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: PDF
      - name: Verify PDF/A
        run: |
          verify Thesis.pdf | grep 'nonCompliant="0"'

  release:
    needs: build
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: PDF
      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: Thesis.pdf
          tag_name: v${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          prerelease: true
          generate_release_notes: true
